branch-defaults:
  master:
    environment: flask-env
    group_suffix: null
environment-defaults:
  flask-env:
    branch: null
    repository: null
global:
  application_name: trade_bot
  branch: null
  default_ec2_keyname: trade_bot
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
